services:
  mysqldb:
    container_name: 'mysqldb'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=blog'
      - 'MYSQL_ROOT_PASSWORD=Abc@1234'
    expose:
      - 13306
    ports:
      - '13306:3306'
    networks:
      - data
    volumes:
      - './db:/var/lib/mysql'
    tty: true
    restart: on-failure

  springapp:
    build: .
    container_name: 'springapp'
    depends_on:
      - 'mysqldb'
    networks:
      - data
    expose:
      - 8080
    ports:
      - '8080:8080'
    volumes:
      - './src:/app/src'
    tty: true


volumes:
  mysql: ~

networks:
  data:
    driver: bridge