services:
  mysqldb:
    container_name: 'mysqldb'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=blog'
      - 'MYSQL_ROOT_PASSWORD=Abc@1234'
    expose:
      - 13306
    ports:
      - '13306:3306'
    networks:
      - data
    volumes:
      - './backend/db:/var/lib/mysql'
    tty: true
    restart: on-failure

  springapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 'springapp'
    depends_on:
      - 'mysqldb'
    networks:
      - data
    expose:
      - 8081
    ports:
      - '8081:8080'
    volumes:
      - './backend/:/app:delegated'
    tty: true

  angularapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 'angularapp'
    depends_on:
      - 'springapp'
    networks:
      - data
    expose:
      - 4200
    ports:
      - '4200:4200'
    volumes:
      - './frontend/:/app:delegated'
      - '/app/node_modules'
    tty: true

volumes:
  mysql: ~

networks:
  data:
    driver: bridge