services:
  mysqldb:
    container_name: 'mysqldb'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=blog'
      - 'MYSQL_ROOT_PASSWORD=Abc@1234'
    expose:
      - 13307
    ports:
      - '13307:3306'
    networks:
      - data
    volumes:
      - './db:/var/lib/mysql'
    tty: true
    restart: on-failure

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'springapp'
    depends_on:
      - 'mysqldb'
    networks:
      - data
    expose:
      - 8082
    ports:
      - '8082:8080'
    volumes:
      - './:/app:delegated'
    tty: true


volumes:
  mysql: ~

networks:
  data:
    driver: bridge